language: node_js
node_js:
  - '8'
install:
  - npm install -g esy@0.3.4
  - esy install
script:
  - esy build
cache:
  timeout: 360
  directories:
    - '$HOME/.esy/'
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
