platform:
    - x64
    - x86

install:
    - npm install -g esy-bash

build_script:
    - esy-bash ./esy-configure --prefix C:/ocaml-bits
    - esy-bash make world.opt
    - esy-bash make install

test: off
